jdk.home.1.7=c:/Program Files/Java/jdk-11
pluginName=AccessHistoryPlugin
version=1.0.0
iiq.home=C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/identityiq
pluginBase=G:/Access_History_Plugin
pluginVersion=1.0.0 
# ant -f build.xml clean package