jdk.home.1.7=c:/Program Files/Java/jdk-11
pluginName=TodoPlugin
version=1.0.1
iiq.home=C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/identityiq
pluginBase=G:/IIQ_Docs
pluginVersion=1.0.1
# ant -f build.xml clean package