jdk.home.17=c:/Program Files/Java/jdk-17
pluginName=QATester
version=1.0.0
iiq.home=C:/Program Files/Apache Software Foundation/Tomcat 9.0/webapps/identityiq
iiq.version=iiq.8.5
pluginBase=G:/IIQ-LCE-Plugin
pluginVersion=1.0.0
# ant -f build.xml clean package